"""Neru Dayo — Voice commands: TTS and fake voice messages."""
import asyncio
import io
import os

import discord
from discord import app_commands
from discord.ext import commands
from gtts import gTTS

from utils.music_manager import FFMPEG_OPTIONS

COLOR_PRIMARY = 0xFFD700
COLOR_SUCCESS = 0x57F287
COLOR_ERROR = 0xED4245


def _generate_tts(text: str, lang: str = "en") -> io.BytesIO:
    """Generate TTS audio as a BytesIO MP3 buffer (blocking — run in executor)."""
    tts = gTTS(text=text, lang=lang, slow=False)
    buf = io.BytesIO()
    tts.write_to_fp(buf)
    buf.seek(0)
    return buf


class Voice(commands.Cog):
    def __init__(self, bot: commands.Bot) -> None:
        self.bot = bot

    # ──────────────────────────── TTS ────────────────────────────
    @app_commands.guild_only()
    @app_commands.command(name="tts", description="Say something in your voice channel with text-to-speech")
    @app_commands.describe(
        text="The text to speak",
        lang="Language code (default: en)",
    )
    async def tts(
        self,
        interaction: discord.Interaction,
        text: str,
        lang: str = "en",
    ) -> None:
        if not interaction.guild:
            return

        member = interaction.guild.get_member(interaction.user.id)
        if not member or not member.voice or not member.voice.channel:
            await interaction.response.send_message(
                "❌ You need to be in a voice channel first.", ephemeral=True
            )
            return

        if len(text) > 200:
            await interaction.response.send_message(
                "❌ Text must be 200 characters or fewer for TTS.", ephemeral=True
            )
            return

        await interaction.response.defer()

        # Generate TTS
        loop = asyncio.get_event_loop()
        try:
            buf = await loop.run_in_executor(None, _generate_tts, text, lang)
        except Exception as e:
            await interaction.followup.send(f"❌ TTS generation failed: `{e}`")
            return

        # Connect / use existing VC
        vc = interaction.guild.voice_client
        if not vc:
            vc = await member.voice.channel.connect()
        elif vc.channel != member.voice.channel:
            await vc.move_to(member.voice.channel)

        if vc.is_playing():
            await interaction.followup.send("❌ Audio is already playing. Wait for it to finish.", ephemeral=True)
            return

        # Play from buffer via FFmpeg
        source = discord.FFmpegPCMAudio(buf, pipe=True, **FFMPEG_OPTIONS)
        done_event = asyncio.Event()

        def after(_err: Exception | None) -> None:
            done_event.set()

        vc.play(source, after=after)

        embed = discord.Embed(
            title="🔊 TTS",
            description=f'*"{text}"*',
            color=COLOR_PRIMARY,
        )
        embed.add_field(name="Language", value=lang)
        embed.add_field(name="Requested by", value=str(interaction.user))
        await interaction.followup.send(embed=embed)

        # Wait for playback to finish (max 60s)
        try:
            await asyncio.wait_for(done_event.wait(), timeout=60)
        except asyncio.TimeoutError:
            pass

    # ──────────────────────────── FAKEVOICE ────────────────────────────
    @app_commands.command(
        name="fakevoice",
        description="Generate a fake voice message audio file from text",
    )
    @app_commands.describe(
        text="The text to convert to a voice message",
        lang="Language code (default: en)",
    )
    async def fakevoice(
        self,
        interaction: discord.Interaction,
        text: str,
        lang: str = "en",
    ) -> None:
        if len(text) > 300:
            await interaction.response.send_message(
                "❌ Text must be 300 characters or fewer.", ephemeral=True
            )
            return

        await interaction.response.defer()

        loop = asyncio.get_event_loop()
        try:
            buf = await loop.run_in_executor(None, _generate_tts, text, lang)
        except Exception as e:
            await interaction.followup.send(f"❌ Audio generation failed: `{e}`")
            return

        embed = discord.Embed(
            title="🎙️ Fake Voice Message",
            description=f'*"{text}"*',
            color=COLOR_PRIMARY,
        )
        embed.add_field(name="Language", value=lang)
        embed.add_field(name="Generated by", value=str(interaction.user))
        embed.set_footer(text="Send this MP3 however you like!")

        file = discord.File(buf, filename="voice_message.mp3")
        await interaction.followup.send(embed=embed, file=file)


async def setup(bot: commands.Bot) -> None:
    await bot.add_cog(Voice(bot))
